Fix compiler warnings
../rai/core_test/network.cpp: In member function 'virtual void network_ipv6_bind_send_ipv4_Test::TestBody()':
../rai/core_test/network.cpp:937:7: error: unused variable 'finish2' [-Werror=unused-variable]
  auto finish2 (false);
       ^~~~~~~
In file included from ../rai/core_test/network.cpp:2:0:
../gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]':
../gtest/include/gtest/gtest.h:1524:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<true>::Compare(const char*, const char*, const T1&, const T2&, typename testing::internal::EnableIf<(! testing::internal::is_pointer<T2>::value)>::type*) [with T1 = int; T2 = long unsigned int; typename testing::internal::EnableIf<(! testing::internal::is_pointer<T2>::value)>::type = void]'
../rai/core_test/network.cpp:41:2:   required from here
../gtest/include/gtest/gtest.h:1448:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (expected == actual) {
       ~~~~~~~~~^~~~~~~~~