Remove unused variable (needs review)
../rai/qt/qt.cpp: In lambda function:
../rai/qt/qt.cpp:1508:10: error: unused variable 'block' [-Werror=unused-variable]
     auto block (this->wallet.wallet_m->change_sync (this->wallet.account, representative_l));
          ^~~~~