Fix compiler warnings
../rai/core_test/node.cpp: In member function 'virtual void node_block_arrival_size_Test::TestBody()':
../rai/core_test/node.cpp:1637:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  for (auto i (0); i < rai::block_arrival::arrival_size_min * 2; ++i)
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../rai/core_test/node.cpp: In member function 'virtual void node_block_arrival_time_Test::TestBody()':
../rai/core_test/node.cpp:1653:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  for (auto i (0); i < rai::block_arrival::arrival_size_min * 2; ++i)
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../rai/core_test/node.cpp:1:0:
../gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperNE(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]':
../rai/core_test/node.cpp:622:2:   required from here
../gtest/include/gtest/gtest.h:1577:28: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
../gtest/include/gtest/gtest.h:1562:7:
   if (val1 op val2) {\
       ~~~~~~~~~
../gtest/include/gtest/gtest.h:1577:28:
 GTEST_IMPL_CMP_HELPER_(NE, !=);

../gtest/include/gtest/gtest.h:1562:12: note: in definition of macro 'GTEST_IMPL_CMP_HELPER_'
   if (val1 op val2) {\
            ^~
../gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperGT(const char*, const char*, const T1&, const T2&) [with T1 = long long unsigned int; T2 = int]':
../rai/core_test/node.cpp:626:2:   required from here
../gtest/include/gtest/gtest.h:1585:28: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
../gtest/include/gtest/gtest.h:1562:7:
   if (val1 op val2) {\
       ~~~~~~~~~
../gtest/include/gtest/gtest.h:1585:28:
 GTEST_IMPL_CMP_HELPER_(GT, >);

../gtest/include/gtest/gtest.h:1562:12: note: in definition of macro 'GTEST_IMPL_CMP_HELPER_'
   if (val1 op val2) {\
            ^~
../gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int]':
../gtest/include/gtest/gtest.h:1484:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = long unsigned int; bool lhs_is_null_literal = false]'
../rai/core_test/node.cpp:42:2:   required from here
../gtest/include/gtest/gtest.h:1448:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (expected == actual) {
       ~~~~~~~~~^~~~~~~~~
../gtest/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int]':
../gtest/include/gtest/gtest.h:1484:23:   required from 'static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int; bool lhs_is_null_literal = false]'
../rai/core_test/node.cpp:1549:2:   required from here
../gtest/include/gtest/gtest.h:1448:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare