Fix compilation warnings
../rai/core_test/block.cpp:49:2:   required from here
../gtest/include/gtest/gtest.h:1577:28: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
../gtest/include/gtest/gtest.h:1562:7:
   if (val1 op val2) {\
       ~~~~~~~~~
../gtest/include/gtest/gtest.h:1577:28:
 GTEST_IMPL_CMP_HELPER_(NE, !=);

../gtest/include/gtest/gtest.h:1562:12: note: in definition of macro 'GTEST_IMPL_CMP_HELPER_'
   if (val1 op val2) {\
            ^~