Fix compilation warnings
../rai/core_test/gap_cache.cpp:26:2:   required from here
../gtest/include/gtest/gtest.h:1448:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (expected == actual) {
       ~~~~~~~~~^~~~~~~~~